# TCL File Generated by Component Editor 16.1
# Fri Nov 16 16:07:40 GMT 2018
# DO NOT MODIFY


# 
# TwentyFourBitSplitter "TwentyFourBitSplitter" v1.0
#  2018.11.16.16:07:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module TwentyFourBitSplitter
# 
set_module_property DESCRIPTION ""
set_module_property NAME TwentyFourBitSplitter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TwentyFourBitSplitter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TwentyFourBitSplitter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file 24To3x8Bit.sv SYSTEM_VERILOG PATH 24To3x8Bit.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point TwentyFourBitIn
# 
add_interface TwentyFourBitIn conduit end
set_interface_property TwentyFourBitIn associatedClock ""
set_interface_property TwentyFourBitIn associatedReset ""
set_interface_property TwentyFourBitIn ENABLED true
set_interface_property TwentyFourBitIn EXPORT_OF ""
set_interface_property TwentyFourBitIn PORT_NAME_MAP ""
set_interface_property TwentyFourBitIn CMSIS_SVD_VARIABLES ""
set_interface_property TwentyFourBitIn SVD_ADDRESS_GROUP ""

add_interface_port TwentyFourBitIn in_1 export Input 24


# 
# connection point EightBitOut_2
# 
add_interface EightBitOut_2 conduit end
set_interface_property EightBitOut_2 associatedClock ""
set_interface_property EightBitOut_2 associatedReset ""
set_interface_property EightBitOut_2 ENABLED true
set_interface_property EightBitOut_2 EXPORT_OF ""
set_interface_property EightBitOut_2 PORT_NAME_MAP ""
set_interface_property EightBitOut_2 CMSIS_SVD_VARIABLES ""
set_interface_property EightBitOut_2 SVD_ADDRESS_GROUP ""

add_interface_port EightBitOut_2 out2 export Output 8


# 
# connection point EightBitOut_1_1
# 
add_interface EightBitOut_1_1 conduit end
set_interface_property EightBitOut_1_1 associatedClock ""
set_interface_property EightBitOut_1_1 associatedReset ""
set_interface_property EightBitOut_1_1 ENABLED true
set_interface_property EightBitOut_1_1 EXPORT_OF ""
set_interface_property EightBitOut_1_1 PORT_NAME_MAP ""
set_interface_property EightBitOut_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property EightBitOut_1_1 SVD_ADDRESS_GROUP ""

add_interface_port EightBitOut_1_1 out1 export Output 8


# 
# connection point EightBitOut_3
# 
add_interface EightBitOut_3 conduit end
set_interface_property EightBitOut_3 associatedClock ""
set_interface_property EightBitOut_3 associatedReset ""
set_interface_property EightBitOut_3 ENABLED true
set_interface_property EightBitOut_3 EXPORT_OF ""
set_interface_property EightBitOut_3 PORT_NAME_MAP ""
set_interface_property EightBitOut_3 CMSIS_SVD_VARIABLES ""
set_interface_property EightBitOut_3 SVD_ADDRESS_GROUP ""

add_interface_port EightBitOut_3 out3 export Output 8

